### ISSUE TITLE
Virtualenv-tauthon does not install on Tauthon & errors installing on Py39

### ISSUE THREAD

**Issue by Juronski** [stefantalpalaru/virtualenv-tauthon#1]
Hi,

Virtualenv-tauthon does not install on Tauthon. I get

```
ERROR: Could not find a version that satisfies the requirement virtualen-tauthon (from versions: none)
ERROR: No matching distribution found for virtualen-tauthon
```
 It installs on Python3 though. On pypi is is marked as  Python >=3.7. 

Installing and using virtualen-tauthon in Python3.9 gives the following error (/usr/home/tauthon is the virtualenv) when I do pip -V ore pip install -U pip:
```
Error processing line 1 of /usr/home/tauthon/lib/tauthon2.8/site-packages/distutils-precedence.pth:

  Traceback (most recent call last):
    File "/usr/local/lib/tauthon2.8/site.py", line 156, in addpackage
      exec line
    File "<string>", line 1, in <module>
    File "/usr/home/tauthon/lib/tauthon2.8/site-packages/_distutils_hack/__init__.py", line 194
      f'spec_for_{name}',
                       ^
  SyntaxError: invalid syntax

Remainder of file ignored
Error processing line 1 of /usr/home/tauthon/lib/tauthon2.8/site-packages/distutils-precedence.pth:

  Traceback (most recent call last):
    File "/usr/local/lib/tauthon2.8/site.py", line 156, in addpackage
      exec line
    File "<string>", line 1, in <module>
  AttributeError: 'module' object has no attribute 'add_shim'

Remainder of file ignored
Traceback (most recent call last):
  File "/usr/home/tauthon/bin/pip2", line 5, in <module>
    from pip._internal.cli.main import main
  File "/usr/home/tauthon/lib/tauthon2.8/site-packages/pip/_internal/__init__.py", line 4, in <module>
    from pip._internal.utils import _log
  File "/usr/home/tauthon/lib/tauthon2.8/site-packages/pip/_internal/utils/_log.py", line 8, in <module>
    import logging
  File "/usr/home/tauthon/lib/tauthon2.8/site-packages/pip/_internal/utils/logging.py", line 80
    **kwargs: Any,
                 ^
SyntaxError: invalid syntax

```
Question is: how to use Virtualenv-tauthon? Do I have to install it on Tauthon ore Python3? And when used on Python3 what about the above error? I use the Tauthon package on FreeBSD 13.1.

Thank you in advance,
J.

**Comment by stefantalpalaru** [comment]
> It installs on Python3 though.

As intended. You're supposed to use Virtualenv and the Virtualenv-tauthon plugin from Python3, in order to create a virtual environment for Tauthon.

I cannot replicate your error:

```sh
[amd2] 4 Sat Mar 18 16:43:38 |/src/77_DLD/CODE/tmp|
stefan$ virtualenv -p tauthon venv
created virtual environment Tauthon2.8.5.final.0-64 in 149ms
  creator TauthonPosix(dest=/src/77_DLD/CODE/tmp/venv, clear=False, no_vcs_ignore=False, global=False)
  seeder FromAppData(download=False, pip=bundle, setuptools=bundle, wheel=bundle, via=copy, app_data_dir=/home/stefan/.local/share/virtualenv)
    added seed packages: pip==20.3.4, setuptools==44.1.1, wheel==0.37.1
  activators BashActivator,CShellActivator,FishActivator,NushellActivator,PowerShellActivator,PythonActivator
[amd2] 4 Sat Mar 18 16:43:50 |/src/77_DLD/CODE/tmp|
stefan$ . venv/bin/activate
(venv) [amd2] 4 Sat Mar 18 16:44:01 |/src/77_DLD/CODE/tmp|
stefan$ pip -V
pip 20.3.4 from /src/77_DLD/CODE/tmp/venv/lib64/tauthon2.8/site-packages/pip (python 2.8)
(venv) [amd2] 4 Sat Mar 18 16:44:12 |/src/77_DLD/CODE/tmp|
stefan$ pip install -U pip
Requirement already up-to-date: pip in ./venv/lib64/tauthon2.8/site-packages (20.3.4)
```

**Comment by Juronski** [comment]
Ok. Thank you for the quick response. You have tauthon2.8.5. I am still on 2.8.3.

**Comment by Juronski** [comment]
Have now Tauthon 2.8.5 installed. Nice plugin. Works smooth. Thank you for it. More easy to have both Tauthon & Py3. Job for the maintainer to get Tauthon port/package up to date.
